Initialized datatset with 800 images.
Initialized datatset with 400 images.
self.seg_included: True
last 2208
freeze layers:
**********************************
12
0 torch.Size([1, 96, 112, 112])
1 torch.Size([1, 96, 112, 112])
2 torch.Size([1, 96, 112, 112])
3 torch.Size([1, 96, 56, 56])
4 torch.Size([1, 384, 56, 56])
5 torch.Size([1, 192, 28, 28])
6 torch.Size([1, 768, 28, 28])
7 torch.Size([1, 384, 14, 14])
8 torch.Size([1, 2112, 14, 14])
9 torch.Size([1, 1056, 7, 7])
10 torch.Size([1, 2208, 7, 7])
11 torch.Size([1, 2208, 7, 7])
************************
Down sample at [0, 3, 5, 7, 9]
Number of out channels [96, 384, 768, 2112, 2208]
From_Layer:0 to_Layer:2
From_Layer:3 to_Layer:4
From_Layer:5 to_Layer:6
From_Layer:7 to_Layer:8
From_Layer:9 to_End
********************
[32m[I 2024-01-19 13:23:32,789][39m A new study created in RDB with name: Study_database
0.125 0.0625 0.25 0.25 0.125
i:1,in_channels:96,out_channels:96
i:2,in_channels:384,out_channels:96
i:3,in_channels:768,out_channels:384
i:4,in_channels:2112,out_channels:768
i:5,in_channels:2208,out_channels:2112
Loading weights
Total parameters in the model: 438.263116
Epoch: 0
Acc: 100.000% (800/800)| CE: 0.0018| Total Loss: 0.1203| IoU :0.0545
Acc: 36.250% (145/400)| CE: 3.0603|  Total Loss: 0.0863| IoU :0.0000
cur_iou:4.5815906949374374e-12,best_iou:4.5815906949374374e-12:
curr_Acc:36.25,best_Acc:36.25:
Epoch:0, Elapsed Time:176.74174976348877
Epoch: 1
[33m[W 2024-01-19 13:27:33,908][39m Trial 0 failed with parameters: {'deconv_layers_3_no_channels': 0.125, 'deconv_layers_5_no_channels': 0.0625, 'atrous_conv_layers_2_no_channels': 0.25, 'atrous_conv_layers_3_no_channels': 0.25, 'max_min_expan_layers_no_channels': 0.125} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/pupil/rmf3mc/Documents/ModelProposing/MGANet/optuna_Final/Train.py", line 284, in objective
    iou,train_acc,train_ce_loss= train_epoch_Seg(epoch)
  File "/home/pupil/rmf3mc/Documents/ModelProposing/MGANet/optuna_Final/Train.py", line 357, in train_epoch_Seg
    iou = iou_binary(preds, masks)
  File "/home/pupil/rmf3mc/Documents/ModelProposing/MGANet/optuna_Final/utils.py", line 82, in iou_binary
    return IoU.item()
KeyboardInterrupt
[33m[W 2024-01-19 13:27:33,909][39m Trial 0 failed with value None.
Traceback (most recent call last):
  File "/home/pupil/rmf3mc/Documents/ModelProposing/MGANet/optuna_Final/Train.py", line 509, in <module>
    study.optimize(objective, n_trials=2, timeout=None,  callbacks=[print_callback])
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/pupil/rmf3mc/Documents/ModelProposing/MGANet/optuna_Final/Train.py", line 284, in objective
    iou,train_acc,train_ce_loss= train_epoch_Seg(epoch)
  File "/home/pupil/rmf3mc/Documents/ModelProposing/MGANet/optuna_Final/Train.py", line 357, in train_epoch_Seg
    iou = iou_binary(preds, masks)
  File "/home/pupil/rmf3mc/Documents/ModelProposing/MGANet/optuna_Final/utils.py", line 82, in iou_binary
    return IoU.item()
KeyboardInterrupt