Initialized datatset with 800 images.
Initialized datatset with 400 images.
Traceback (most recent call last):
  File "/home/pupil/rmf3mc/Documents/ModelProposing/MGANet/optuna_Final/Train.py", line 506, in <module>
    study = optuna.create_study(study_name='Study_database', storage='sqlite:///{db_file_path}',
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/_convert_positional_args.py", line 83, in converter_wrapper
    return func(**kwargs)
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/study/study.py", line 1246, in create_study
    storage = storages.get_storage(storage)
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/storages/__init__.py", line 43, in get_storage
    return _CachedStorage(RDBStorage(storage))
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 206, in __init__
    self.url = self._fill_storage_url_template(url)
  File "/home/pupil/rmf3mc/.conda/envs/UnetCRF2/lib/python3.10/site-packages/optuna/storages/_rdb/storage.py", line 940, in _fill_storage_url_template
    return template.format(SCHEMA_VERSION=models.SCHEMA_VERSION)
KeyError: 'db_file_path'